language: node_js
os: linux
sudo: required
dist: xenial
group: travis_lts
addons:
  sources:
    - ubuntu-toolchain-r-test
addons:
  chrome: stable
node_js:
  - '10'
cache:
  npm: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
install:
  - npm i -g npm@6.11.3
  - npm ci

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - ken.martin@kitware.com
      - matt.mccormick@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - doc/build-tmp

script:
  - npm ci
  - npm run build:release
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/itk-vtk-viewer.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
