name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node: [8, 10, 12]
    name: ${{ matrix.os }} and node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        if: ${{ runner.os == 'Linux' }}
        run: |
          # Allow writing test/output.html
          sudo chmod 777 test
          # To debug, run `./test/run.sh -d`
          ./test/run.sh

      - uses: ashley-taylor/junit-report-annotations-action@v1.0
        if: ${{ always() && runner.os == 'ubuntu-18.04' }}
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: 'test/TESTS-*.xml'

      - uses: actions/upload-artifact@v1
        if: ${{ always() && runner.os == 'ubuntu-18.04' }}
        with:
          name: 'Node${{ matrix.node}}TestOutput'
          path: test/output.html
